
    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    

    '***************************************************
    'Function maps
    '***************************************************
    function RBSFM_getFunctionsForFile(filename)
  map = {
    "test__CarShowProcessor":RBSFM_getFunctions_test__CarShowProcessor 
    "rooibosDist":RBSFM_getFunctions_rooibosDist 
    "rooibosFunctionMap":RBSFM_getFunctions_rooibosFunctionMap 
  } 
  return map[filename]
end function

function RBSFM_getFunctions_test__CarShowProcessor()
  return {
    "CSP__TestInvalidData":CSP__TestInvalidData 
    "CSP__TestEmptyData":CSP__TestEmptyData 
    "CSP__TestValidData":CSP__TestValidData 
  } 

end function

function RBSFM_getFunctions_rooibosDist()
  return {
    "Rooibos__Init":Rooibos__Init 
    "BaseTestSuite":BaseTestSuite 
    "RBS_BTS_AddTest":RBS_BTS_AddTest 
    "RBS_BTS_CreateTest":RBS_BTS_CreateTest 
    "RBS_BTS_Fail":RBS_BTS_Fail 
    "RBS_BTS_GetLegacyCompatibleReturnValue":RBS_BTS_GetLegacyCompatibleReturnValue 
    "RBS_BTS_AssertFalse":RBS_BTS_AssertFalse 
    "RBS_BTS_AssertTrue":RBS_BTS_AssertTrue 
    "RBS_BTS_AssertEqual":RBS_BTS_AssertEqual 
    "RBS_BTS_AssertLike":RBS_BTS_AssertLike 
    "RBS_BTS_AssertNotEqual":RBS_BTS_AssertNotEqual 
    "RBS_BTS_AssertInvalid":RBS_BTS_AssertInvalid 
    "RBS_BTS_AssertNotInvalid":RBS_BTS_AssertNotInvalid 
    "RBS_BTS_AssertAAHasKey":RBS_BTS_AssertAAHasKey 
    "RBS_BTS_AssertAANotHasKey":RBS_BTS_AssertAANotHasKey 
    "RBS_BTS_AssertAAHasKeys":RBS_BTS_AssertAAHasKeys 
    "RBS_BTS_AssertAANotHasKeys":RBS_BTS_AssertAANotHasKeys 
    "RBS_BTS_AssertArrayContains":RBS_BTS_AssertArrayContains 
    "RBS_BTS_AssertArrayContainsAAs":RBS_BTS_AssertArrayContainsAAs 
    "RBS_BTS_AssertArrayNotContains":RBS_BTS_AssertArrayNotContains 
    "RBS_BTS_AssertArrayContainsSubset":RBS_BTS_AssertArrayContainsSubset 
    "RBS_BTS_AssertArrayNotContainsSubset":RBS_BTS_AssertArrayNotContainsSubset 
    "RBS_BTS_AssertArrayCount":RBS_BTS_AssertArrayCount 
    "RBS_BTS_AssertArrayNotCount":RBS_BTS_AssertArrayNotCount 
    "RBS_BTS_AssertEmpty":RBS_BTS_AssertEmpty 
    "RBS_BTS_AssertNotEmpty":RBS_BTS_AssertNotEmpty 
    "RBS_BTS_AssertArrayContainsOnlyValuesOfType":RBS_BTS_AssertArrayContainsOnlyValuesOfType 
    "RBS_CMN_GetIsTypeFunction":RBS_CMN_GetIsTypeFunction 
    "RBS_BTS_AssertType":RBS_BTS_AssertType 
    "RBS_BTS_AssertSubType":RBS_BTS_AssertSubType 
    "RBS_BTS_EqValues":RBS_BTS_EqValues 
    "RBS_BTS_EqAssocArray":RBS_BTS_EqAssocArray 
    "RBS_BTS_EqArray":RBS_BTS_EqArray 
    "RBS_BTS_AssertNodeCount":RBS_BTS_AssertNodeCount 
    "RBS_BTS_AssertNodeNotCount":RBS_BTS_AssertNodeNotCount 
    "RBS_BTS_AssertNodeEmpty":RBS_BTS_AssertNodeEmpty 
    "RBS_BTS_AssertNodeNotEmpty":RBS_BTS_AssertNodeNotEmpty 
    "RBS_BTS_AssertNodeContains":RBS_BTS_AssertNodeContains 
    "RBS_BTS_AssertNodeContainsOnly":RBS_BTS_AssertNodeContainsOnly 
    "RBS_BTS_AssertNodeNotContains":RBS_BTS_AssertNodeNotContains 
    "RBS_BTS_AssertNodeContainsFields":RBS_BTS_AssertNodeContainsFields 
    "RBS_BTS_AssertNodeNotContainsFields":RBS_BTS_AssertNodeNotContainsFields 
    "RBS_BTS_AssertAAContainsSubset":RBS_BTS_AssertAAContainsSubset 
    "RBS_BTS_Stub":RBS_BTS_Stub 
    "RBS_BTS_ExpectOnce":RBS_BTS_ExpectOnce 
    "RBS_BTS_ExpectOnceOrNone":RBS_BTS_ExpectOnceOrNone 
    "RBS_BTS_ExpectNone":RBS_BTS_ExpectNone 
    "RBS_BTS_Expect":RBS_BTS_Expect 
    "RBS_BTS_Mock":RBS_BTS_Mock 
    "RBS_BTS_CreateFake":RBS_BTS_CreateFake 
    "RBS_BTS_AssertMocks":RBS_BTS_AssertMocks 
    "RBS_CMN_IsXmlElement":RBS_CMN_IsXmlElement 
    "RBS_CMN_IsFunction":RBS_CMN_IsFunction 
    "RBS_CMN_GetFunction":RBS_CMN_GetFunction 
    "RBS_CMN_GetFunctionBruteForce":RBS_CMN_GetFunctionBruteForce 
    "RBS_CMN_IsBoolean":RBS_CMN_IsBoolean 
    "RBS_CMN_IsInteger":RBS_CMN_IsInteger 
    "RBS_CMN_IsFloat":RBS_CMN_IsFloat 
    "RBS_CMN_IsDouble":RBS_CMN_IsDouble 
    "RBS_CMN_IsLongInteger":RBS_CMN_IsLongInteger 
    "RBS_CMN_IsNumber":RBS_CMN_IsNumber 
    "RBS_CMN_IsList":RBS_CMN_IsList 
    "RBS_CMN_IsArray":RBS_CMN_IsArray 
    "RBS_CMN_IsAssociativeArray":RBS_CMN_IsAssociativeArray 
    "RBS_CMN_IsSGNode":RBS_CMN_IsSGNode 
    "RBS_CMN_IsString":RBS_CMN_IsString 
    "RBS_CMN_IsNotEmptyString":RBS_CMN_IsNotEmptyString 
    "RBS_CMN_IsDateTime":RBS_CMN_IsDateTime 
    "RBS_CMN_IsValid":RBS_CMN_IsValid 
    "RBS_CMN_IsUndefined":RBS_CMN_IsUndefined 
    "RBS_CMN_ValidStr":RBS_CMN_ValidStr 
    "RBS_CMN_AsString":RBS_CMN_AsString 
    "RBS_CMN_AsInteger":RBS_CMN_AsInteger 
    "RBS_CMN_AsLongInteger":RBS_CMN_AsLongInteger 
    "RBS_CMN_AsFloat":RBS_CMN_AsFloat 
    "RBS_CMN_AsDouble":RBS_CMN_AsDouble 
    "RBS_CMN_AsBoolean":RBS_CMN_AsBoolean 
    "RBS_CMN_AsArray":RBS_CMN_AsArray 
    "RBS_CMN_IsNullOrEmpty":RBS_CMN_IsNullOrEmpty 
    "RBS_CMN_FindElementIndexInArray":RBS_CMN_FindElementIndexInArray 
    "RBS_CMN_ArrayContains":RBS_CMN_ArrayContains 
    "RBS_CMN_FindElementIndexInNode":RBS_CMN_FindElementIndexInNode 
    "RBS_CMN_NodeContains":RBS_CMN_NodeContains 
    "RBS_ItG_GetTestCases":RBS_ItG_GetTestCases 
    "RBS_ItG_GetRunnableTestSuite":RBS_ItG_GetRunnableTestSuite 
    "ItemGenerator":ItemGenerator 
    "RBS_IG_GetItem":RBS_IG_GetItem 
    "RBS_IG_GetAssocArray":RBS_IG_GetAssocArray 
    "RBS_IG_GetArray":RBS_IG_GetArray 
    "RBS_IG_GetSimpleType":RBS_IG_GetSimpleType 
    "RBS_IG_GetBoolean":RBS_IG_GetBoolean 
    "RBS_IG_GetInteger":RBS_IG_GetInteger 
    "RBS_IG_GetFloat":RBS_IG_GetFloat 
    "RBS_IG_GetString":RBS_IG_GetString 
    "UnitTestRuntimeConfig":UnitTestRuntimeConfig 
    "RBS_CreateSuites":RBS_CreateSuites 
    "RBS_STATS_CreateTotalStatistic":RBS_STATS_CreateTotalStatistic 
    "RBS_STATS_MergeTotalStatistic":RBS_STATS_MergeTotalStatistic 
    "RBS_STATS_CreateSuiteStatistic":RBS_STATS_CreateSuiteStatistic 
    "RBS_STATS_CreateTestStatistic":RBS_STATS_CreateTestStatistic 
    "RBS_STATS_AppendTestStatistic":RBS_STATS_AppendTestStatistic 
    "RBS_STATS_AppendSuiteStatistic":RBS_STATS_AppendSuiteStatistic 
    "UnitTestCase":UnitTestCase 
    "RBS_TC_AddAssertLine":RBS_TC_AddAssertLine 
    "RBS_TC_GetAssertLine":RBS_TC_GetAssertLine 
    "Logger":Logger 
    "RBS_LOGGER_PrintStatistic":RBS_LOGGER_PrintStatistic 
    "RBS_LOGGER_PrintSuiteStatistic":RBS_LOGGER_PrintSuiteStatistic 
    "RBS_LOGGER_PrintTestStatistic":RBS_LOGGER_PrintTestStatistic 
    "RBS_LOGGER_FillText":RBS_LOGGER_FillText 
    "RBS_LOGGER_PrintStart":RBS_LOGGER_PrintStart 
    "RBS_LOGGER_PrintEnd":RBS_LOGGER_PrintEnd 
    "RBS_LOGGER_PrintSuiteSetUp":RBS_LOGGER_PrintSuiteSetUp 
    "RBS_LOGGER_PrintMetaSuiteStart":RBS_LOGGER_PrintMetaSuiteStart 
    "RBS_LOGGER_PrintSuiteStart":RBS_LOGGER_PrintSuiteStart 
    "RBS_LOGGER_PrintSuiteTearDown":RBS_LOGGER_PrintSuiteTearDown 
    "RBS_LOGGER_PrintTestSetUp":RBS_LOGGER_PrintTestSetUp 
    "RBS_LOGGER_PrintTestTearDown":RBS_LOGGER_PrintTestTearDown 
    "UnitTestResult":UnitTestResult 
    "RBS_TRes_Reset":RBS_TRes_Reset 
    "RBS_TRes_AddResult":RBS_TRes_AddResult 
    "RBS_TRes_GetResult":RBS_TRes_GetResult 
    "RBS_TR_TestRunner":RBS_TR_TestRunner 
    "RBS_TR_Run":RBS_TR_Run 
    "RBS_RT_RunItGroups":RBS_RT_RunItGroups 
    "RBS_RT_RunTestCases":RBS_RT_RunTestCases 
    "RBS_TR_SendHomeKeypress":RBS_TR_SendHomeKeypress 
    "Rooibos_RunNodeTests":Rooibos_RunNodeTests 
    "Rooibos_CreateTestNode":Rooibos_CreateTestNode 
  } 

end function

function RBSFM_getFunctions_rooibosFunctionMap()
  return {
    "RBSFM_getFunctions_test__CarShowProcessor":RBSFM_getFunctions_test__CarShowProcessor 
    "RBSFM_getFunctions_rooibosDist":RBSFM_getFunctions_rooibosDist 
    "RBSFM_getFunctions_rooibosFunctionMap":RBSFM_getFunctions_rooibosFunctionMap 
    "RBSFM_getFilenames":RBSFM_getFilenames 
  } 

end function

function RBSFM_getFilenames()
  return [
    "test__CarShowProcessor", 
    "rooibosDist", 
    "rooibosFunctionMap", 
  ] 
end function



    '***************************************************
    ' Unit test suites defitintions
    '***************************************************
    

    function RBSFM_getTestSuitesForProject()
        return [
        
{
      name: "[CSP]"
      filePath: "pkg:/source/tests/Source/test__CarShowProcessorbrs"
      valid: true
      hasFailures: false
      hasSoloTests: false
      hasIgnoredTests: false
      hasSoloGroups: false
      isSolo: false
      isIgnored: false
      itGroups: [
      {
        testCases: [
        {
          isSolo: false
          funcName: "CSP__TestInvalidData"
          isIgnored: false
          isParamTest: false
          name: "CSP__TestInvalidData"
          lineNumber: 13
          paramLineNumber: 0
          assertIndex: 1
          assertLineNumberMap: {"0":17}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "CSP__TestEmptyData"
          isIgnored: false
          isParamTest: false
          name: "CSP__TestEmptyData"
          lineNumber: 21
          paramLineNumber: 0
          assertIndex: 1
          assertLineNumberMap: {"0":25}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "CSP__TestValidData"
          isIgnored: false
          isParamTest: true
          name: "CSP__TestValidData0"
          lineNumber: 32
          paramLineNumber: 29
          assertIndex: 3
          assertLineNumberMap: {"0":37,"1":40,"2":42}
          rawParams: [true,[{"name":"New York Car Show","cars":[{"make":"Hondaka","model":"Elisa"},{"make":"George Motors","model":"George 15"},{"make":"Julio Mechannica","model":"Mark 1"},{"make":"Moto Tourismo","model":"Cyclissimo"},{"make":"Edison Motors","model":""}]},{"name":"Melbourne Motor Show","cars":[{"make":"Julio Mechannica","model":"Mark 4S"},{"make":"Hondaka","model":"Elisa"},{"make":"Moto Tourismo","model":"Cyclissimo"},{"make":"George Motors","model":"George 15"},{"make":"Moto Tourismo","model":"Delta 4"}]},{"name":"Cartopia","cars":[{"make":"Moto Tourismo","model":"Cyclissimo"},{"make":"George Motors","model":"George 15"},{"make":"Hondaka","model":"Ellen"},{"make":"Moto Tourismo","model":"Delta 16"},{"make":"Moto Tourismo","model":"Delta 4"},{"make":"Julio Mechannica","model":"Mark 2"}]},{"name":"Carographic","cars":[{"make":"Hondaka","model":"Elisa"},{"make":"Hondaka","model":"Elisa"},{"make":"Julio Mechannica","model":"Mark 4"},{"make":"Julio Mechannica","model":"Mark 2"},{"make":"Moto Tourismo"},{"make":"Julio Mechannica","model":"Mark 4"}]},{"cars":[{"make":"Moto Tourismo","model":"Delta 4"}]}],"Hondaka     Elisa         New York Car Show         Melbourne Motor Show         Carographic     Ellen         Cartopia George Motors     George 15         New York Car Show         Melbourne Motor Show         Cartopia Julio Mechannica     Mark 1         New York Car Show     Mark 4S         Melbourne Motor Show     Mark 2         Cartopia         Carographic     Mark 4         Carographic Moto Tourismo     Cyclissimo         New York Car Show         Melbourne Motor Show         Cartopia     Delta 4         Melbourne Motor Show         Cartopia     Delta 16         Cartopia "]
          paramTestIndex: 0
          expectedNumberOfParams: 3
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "CSP__TestValidData"
          isIgnored: false
          isParamTest: true
          name: "CSP__TestValidData1"
          lineNumber: 32
          paramLineNumber: 30
          assertIndex: 3
          assertLineNumberMap: {"0":37,"1":40,"2":42}
          rawParams: [false,[{"name":"New York Car Show","cars":[{"make":"Hondaka","model":""},{"make":"George Motors","model":"George 15"},{"make":"Julio Mechannica","model":"Mark 1"},{"make":"Moto Tourismo","model":"Cyclissimo"},{"make":"Edison Motors","model":""}]},{"name":"Melbourne Motor Show","cars":[{"make":"Julio Mechannica","model":"Mark 4S"},{"make":"Hondaka","model":"Elisa"},{"make":"Moto Tourismo","model":"Cyclissimo"},{"make":"George Motors","model":"George 15"},{"make":"Moto Tourismo","model":"Delta 4"}]},{"name":"Cartopia","cars":[{"make":"Moto Tourismo","model":"Cyclissimo"},{"make":"George Motors","model":"George 15"},{"make":"Hondaka","model":"Ellen"},{"make":"Moto Tourismo","model":"Delta 16"},{"make":"Moto Tourismo","model":"Delta 4"},{"make":"Julio Mechannica","model":"Mark 2"}]},{"name":"Carographic","cars":[{"make":"Hondaka","model":"Elisa"},{"make":"Hondaka","model":"Elisa"},{"make":"Julio Mechannica","model":"Mark 4"},{"make":"Julio Mechannica","model":"Mark 2"},{"make":"Moto Tourismo"},{"make":"Julio Mechannica","model":"Mark 4"}]},{"cars":[{"make":"Moto Tourismo","model":"Delta 4"}]}],"Hondaka     Elisa         New York Car Show         Melbourne Motor Show         Carographic     Ellen         Cartopia George Motors     George 15         New York Car Show         Melbourne Motor Show         Cartopia Julio Mechannica     Mark 1         New York Car Show     Mark 4S         Melbourne Motor Show     Mark 2         Cartopia         Carographic     Mark 4         Carographic Moto Tourismo     Cyclissimo         New York Car Show         Melbourne Motor Show         Cartopia     Delta 4         Melbourne Motor Show         Cartopia     Delta 16         Cartopia "]
          paramTestIndex: 1
          expectedNumberOfParams: 3
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "CSP__TestValidData"
          isIgnored: false
          isParamTest: true
          name: "CSP__TestValidData2"
          lineNumber: 32
          paramLineNumber: 31
          assertIndex: 3
          assertLineNumberMap: {"0":37,"1":40,"2":42}
          rawParams: [false,[{"name":"New York Car Show","cars":[{"make":"George Motors","model":"George 15"},{"make":"Julio Mechannica","model":"Mark 1"},{"make":"Moto Tourismo","model":"Cyclissimo"},{"make":"Edison Motors","model":""}]},{"name":"Melbourne Motor Show","cars":[{"make":"Julio Mechannica","model":"Mark 4S"},{"make":"Hondaka","model":"Elisa"},{"make":"Moto Tourismo","model":"Cyclissimo"},{"make":"George Motors","model":"George 15"},{"make":"Moto Tourismo","model":"Delta 4"}]},{"name":"Cartopia","cars":[{"make":"Moto Tourismo","model":"Cyclissimo"},{"make":"George Motors","model":"George 15"},{"make":"Hondaka","model":"Ellen"},{"make":"Moto Tourismo","model":"Delta 16"},{"make":"Moto Tourismo","model":"Delta 4"},{"make":"Julio Mechannica","model":"Mark 2"}]},{"name":"Carographic","cars":[{"make":"Hondaka","model":"Elisa"},{"make":"Hondaka","model":"Elisa"},{"make":"Julio Mechannica","model":"Mark 4"},{"make":"Julio Mechannica","model":"Mark 2"},{"make":"Moto Tourismo"},{"make":"Julio Mechannica","model":"Mark 4"}]},{"cars":[{"make":"Moto Tourismo","model":"Delta 4"}]}],"Hondaka     Elisa         New York Car Show         Melbourne Motor Show         Carographic     Ellen         Cartopia George Motors     George 15         New York Car Show         Melbourne Motor Show         Cartopia Julio Mechannica     Mark 1         New York Car Show     Mark 4S         Melbourne Motor Show     Mark 2         Cartopia         Carographic     Mark 4         Carographic Moto Tourismo     Cyclissimo         New York Car Show         Melbourne Motor Show         Cartopia     Delta 4         Melbourne Motor Show         Cartopia     Delta 16         Cartopia "]
          paramTestIndex: 2
          expectedNumberOfParams: 3
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "test__CarShowProcessor"
        setupFunctionName: ""
        tearDownFunctionName: ""
        beforeEachFunctionName: ""
        afterEachFunctionName: ""
        isSolo: false
        isIgnored: false
        hasSoloTests: false
        name: "Data Processing Tests"
      }]
      setupFunctionName: ""
      tearDownFunctionName: ""
      isNodeTest: false
      nodeTestFileName: ""
      beforeEachFunctionName: ""
      afterEachFunctionName: ""
    },

      ]
    end function



    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    